---
title: "Course Project Part 1"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    runtime: shiny
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(shiny)
library(leaflet)
```

```{r}
ames_student <- read_csv("ames_student.csv")

ames_student <- ames_student %>% mutate_if(is.character, as_factor)
```


Column {data-width=350}
-----------------------------------------------------------------------

### Map

```{r}
colorpal <- colorFactor(palette = "RdYlBu", ames_student$Above_Median)

ames_map <- leaflet() %>% setView(lng = -93.64, lat = 42.02, zoom = 12) %>%
  addTiles() %>%
  addCircleMarkers(data = ames_student, lng = ~Longitude, lat = ~Latitude, 
    weight = 1.5, radius = 1, color = ~colorpal(Above_Median)) %>%
  addLegend(data = ames_student, position = "bottomright", pal = colorpal, 
    values = ~Above_Median)

ames_map
```

### Neighborhood

```{r}
ggplot(ames_student, aes(x = Neighborhood, fill = Above_Median)) +
  geom_bar() + theme(axis.text.x = element_text(size = 8, angle = 90)) +
  labs(title = "Neighborhood and Above Median Price",
       y = "Count")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Year Built

```{r}
ggplot(ames_student, aes(x = Year_Built, y = Above_Median)) +
  geom_boxplot() +
  labs(title = "Year Built and Above Median Price",
       x = "Year Built",
       y = "Sale Price Above Median")
```

### Above Grade Living Area

```{r}
ggplot(ames_student, aes(x = Gr_Liv_Area, y = Above_Median)) +
  geom_boxplot() +
  labs(title = "Above Grade Living Area and Above Median Price",
       x = "Above Grade Living Area Square Feet",
       y = "Sale Price Above Median")
```

